name: Core
main: unhappy.legendzrpg.plugin.Main
version: 0.0.1
description: LegendzRPG Plugin

commands:
  shop:
    description: Test GUI
  fly:
    description: Fly
  notify:
    description: Turns Notify on/off
  givept:
    description: Admin Command